### ISSUE TITLE
华为 小米手机都有这个问题

### ISSUE THREAD

**Issue by WuGang128** [zzz40500/HeadsUp#4]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.mingle.headupdemo, PID: 8219
                                                                     java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.mingle.headupdemo/0x109008c vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 actions=1 vis=PRIVATE)
                                                                         at android.app.NotificationManager.notifyAsUser(NotificationManager.java:318)
                                                                         at android.app.NotificationManager.notify(NotificationManager.java:293)
                                                                         at android.app.NotificationManager.notify(NotificationManager.java:277)
                                                                         at com.mingle.headsUp.HeadsUpManager.show(HeadsUpManager.java:125)

**Comment by WuGang128** [comment]
public Builder setSmallIcon(int icon) {
            headsUp.setIcon(icon);
         // super.setSmallIcon(icon);
            return this;
        }
这里为什么注释了呢。 打开注释 小米华为就能正常使用， 但是不知道会有什么问题

**Comment by l1x2d3** [comment]
我也遇到这种问题
